### ISSUE TITLE
Move the docs / website / blog to Gatsby and Post-MVP TODO

### ISSUE THREAD

**Issue by torch2424** [wasmerio/docs.wasmer.io#7]
# Moving the site

@syrusakbary and I agreed to get the docs out sooner rather than later, but we want to move all of the online Wasmer Resources under a single domain and repo on Gatsby 😄 

# Post MVP TODO

* [ ] [Only show parts of the example?](https://docs.wasmer.io/runtime/c-integration/examples/passing-data/runtime-c-integration-examples-passing-data)
* [ ] Add a way to include files from markdown to be able to show their source code. 
* [ ] Add the Wasmer Logo to the header, and change header color? Actually, with the move, just re-use the same header component

**Comment by syrusakbary** [comment]
We don’t need this any longer :)
Closing the issue
